# Generated by Django 3.2 on 2022-01-15 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_customuser_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='year',
            field=models.TextField(default=0),
        ),
    ]
