# Generated by Django 3.2 on 2022-01-10 18:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('whatthegam', '0001_initial'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='whatthegam.school'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='year',
            field=models.IntegerField(null=True),
        ),
    ]
