# Generated by Django 3.2 on 2022-01-10 18:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('whatthegam', '0001_initial'),
        ('accounts', '0002_auto_20220111_0313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='school',
            field=models.ForeignKey(default='snu', on_delete=django.db.models.deletion.CASCADE, to='whatthegam.school'),
        ),
    ]
