# Generated by Django 3.2 on 2022-01-13 01:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('whatthegam', '0001_initial'),
        ('accounts', '0003_alter_profile_school'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='school',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='whatthegam.school'),
        ),
    ]
