# Generated by Django 3.2 on 2022-01-15 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Text',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('created_dt', models.DateTimeField(auto_now=True)),
                ('x_axis', models.FloatField(default=0.0)),
                ('y_axis', models.FloatField(default=0.0)),
            ],
        ),
    ]
