# Generated by Django 3.2 on 2022-01-15 16:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('whatthegam', '0001_initial'),
        ('texts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='text',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='text',
            name='written_place',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='whatthegam.place'),
        ),
    ]
