# Generated by Django 3.2 on 2022-01-12 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('texts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='text',
            old_name='written_school',
            new_name='written_place',
        ),
    ]
